service/forms/upload.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField


class FileForm(FlaskForm):
    file = FileField()

service/app.py
from flask import Flask

from service import config
from service.views import files, index

app_config = config.load_from_env()


def create_app() -> Flask:
    app = Flask(__name__)

    app.config['SECRET_KEY'] = app_config.web.secret_key

    app.register_blueprint(index.view)
    app.register_blueprint(files.view, url_prefix='/files')

    return app

service/views/files.py
import logging

from flask import Blueprint, redirect, render_template, request, url_for

from service.repos import files
from service.schemas import FileSettings

logger = logging.getLogger(__name__)

view = Blueprint('files', __name__)


@view.get('/card')
def file_card():
    filename = request.args.get('filename')
    suffix = request.args.get('suffix')

    if not (filename and suffix):
        return render_template('mistake.html')

    file_data = files.internal_data(filename, suffix)
    return render_template(
        'file_card.html',
        columns=file_data.columns,
        data=file_data.data,
        file={'name': filename, 'suffix': suffix},
    )


@view.get('/hunter')
def anomaly_hunter():
    filename = request.args.get('filename')
    suffix = request.args.get('suffix')

    if not (filename and suffix):
        return render_template('mistake.html')

    if not files.find_anomaly(filename, suffix):
        return render_template('mistake.html')

    return redirect(url_for('index.index'))


@view.get('/settings')
def file_settings():
    filename = request.args.get('filename')
    suffix = request.args.get('suffix')
    sheet = request.args.get('sheet')

    if not (filename and suffix):
        return render_template('mistake.html')

    yaml_sheet = files.yaml_sheet(filename)

    if not (sheet or yaml_sheet):
        logger.debug(sheet)
        sheets = files.get_sheets(filename, suffix)
        logger.debug(sheets)
        return render_template(
            'file_sheets.html',
            sheets=sheets,
            file={'name': filename, 'suffix': suffix},
        )

    if not sheet:
        if not yaml_sheet:
            return render_template('mistake.html')
        sheet = yaml_sheet

    files.sheet_to_yaml(filename, sheet)
    file_data = files.short_data(filename, suffix, sheet)
    return render_template(
        'file_sheet.html',
        columns=file_data.columns,
        data=file_data.data,
        file={'name': filename, 'sheet': sheet},
    )


@view.route('/settings/save', methods=['GET', 'POST'])
def save_settings():
    filename = request.args.get('filename')    
    sheet = request.args.get('sheet')
    base_column = request.form.get('base_col')
    compare_column = request.form.get('compare_col')
    precision = request.form.get('precision')

    settings = FileSettings(
        sheet=sheet,
        base_column=base_column,
        compare_column=compare_column,
        precision=precision,
    )
    if not filename:
        return render_template('mistake.html')

    files.settings_to_yaml(filename, settings)
    return redirect(url_for('files.file_card', filename=filename, suffix='.xlsx'))

service/views/index.py
from flask import Blueprint, redirect, render_template, request, url_for

from service import config
from service.repos import index as ind
from service.forms.upload import FileForm

app_config = config.load_from_env()
view = Blueprint('index', __name__)
upload_dir = app_config.path.upload_dir


@view.route('/', methods=['GET', 'POST'])
def index():
    title = 'Поиск аномалий'
    data_files = ind.get_files()
    file_list = [file.dict() for file in data_files]

    form = FileForm(meta={'csrf': False})
    if form.validate_on_submit():
        file = request.files['file']
        upload_file = upload_dir / str(file.filename)
        file.save(upload_file)
        ind.yaml_create(upload_file.stem)
        return redirect(url_for('index.index'))

    return render_template(
        'index.html',
        page_title=title,
        form=form,
        file_list=file_list,
    )

service/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" media="print" href="{{ url_for('static', filename='print.css') }}" />
    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

service/templates/file_card.html
{% extends "base.html" %}

{% block content %}

<a href="{{ url_for('files.file_settings') }}?filename={{ file.name }}&suffix={{ file.suffix }}" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Сделать настройки</a>
<a href="{{ url_for('files.anomaly_hunter') }}?filename={{ file.name }}&suffix={{ file.suffix }}" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Обработать</a>

<table class="table table-hover table-dark">
    <thead>
      <tr>
        {% for column in columns %}
        <th scope="col">{{ column }}</th>
        {% endfor %}        
      </tr>
    </thead>
    <tbody>
      {% for row in data %}  
      <tr>
        {% for column in columns %}        
        <td>{{ row[column] }}</td>
        {% endfor %}        
      </tr>
      {% endfor %}
      
    </tbody>
  </table>

{% endblock %}

service/templates/file_sheet.html
{% extends "base.html" %}

{% block content %}

<form action="{{ url_for('files.save_settings') }}?filename={{ file.name }}&sheet={{ file.sheet }}" enctype="multipart/form-data" method="post">
    <div class="container">
        <div class="row">
          <div class="col-sm"><h2>Параметры настройки файла {{ file.name }} на странице {{ file.sheet }}</h2></div>
        </div>        
        <div class="row">
          <div class="col-sm">
            Колонка наименования
          </div>
          <div class="col-sm">
            Точность совпадения наименований
          </div>
          <div class="col-sm">
            Колонка сравнения
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <select class="form-control" name="base_col">
                {% for column in columns %}
                <option>{{ column }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="col-sm">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text">$</span>
                </div>
                <input type="text" class="form-control" name="precision">
                <div class="input-group-append">
                  <span class="input-group-text">.00</span>
                </div>
              </div>
          </div>
          <div class="col-sm">
            <select class="form-control" name="compare_col">
                {% for column in columns %}
                <option>{{ column }}</option>
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="row">
            <p></p>
            <div class="col-sm"><button type="submit" class="btn btn-primary mb-2">Сохранить настройки</button></div>
        </div>
      </div>
</form>

<table class="table">
    <thead>
      <tr>
        {% for column in columns %}
        <th scope="col">{{ column }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for row in data %}
      <tr>
        {% for column in columns %}
        <td>{{ row[column] }}</td>
        {% endfor %}
      </tr>
      {% endfor %}

    </tbody>
  </table>

{% endblock %}

service/templates/file_sheets.html
{% extends "base.html" %}

{% block content %}



<table class="table table-hover table-dark">
    <thead>
      <tr>
        {% for sheet in sheets %}
        <th scope="col">ЛИСТ EXCEL</th>
        {% endfor %}        
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for sheet in sheets %}       
        <td><a href="{{ url_for('files.file_settings') }}?filename={{ file.name }}&suffix={{ file.suffix }}&sheet={{ sheet }}">{{ sheet }}</a></td>
        {% endfor %}        
      </tr>      
    </tbody>
  </table>

выбор страницы

выбор диапазона чтения таблицы

выбор колонки наименований

выбор колонки для сравнения (проверки) значений

точность совпадения наименований (от 0 до 1, где 1 это 100% совпадение)


{% endblock %}

service/templates/index.html
{% extends "base.html" %}

{% block content %}


<div class="card">
    <h5 class="card-header">Загрузите и отправте файл для обработки на сервер</h5>
    <div class="card-body">
        {{ form.hidden_tag() }}
        <form action="{{ url_for('index.index') }}" enctype="multipart/form-data" method="post">
            <div class="form-group">
                {{ form.file }}
            </div>
            <p></p>
            <button type="submit" class="btn btn-success">Отправить</button>
        </form>
    </div>
</div>
<p></p>  
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for file in file_list %}
    <div class="card" style="width:auto;">
        <div class="card-body">
          <h6 class="card-title">Документ 1С Предприятие (отчет по ОС)</h6>
          <h7 class="card-subtitle mb-2 text-muted"> Название файла - {{ file.name }}{{ file.suffix }} </h7>
          <p></p>
          <h7 class="card-subtitle mb-2 text-muted"> Дата документа - {{ file.date.strftime('%Y-%m-%d') }} </h7>
          <p></p>
          <a href="{{ url_for('files.file_card') }}?filename={{ file.name }}&suffix={{ file.suffix }}" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Открыть</a>
          <a href="{{ url_for('files.anomaly_hunter') }}?filename={{ file.name }}&suffix={{ file.suffix }}" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Обработать</a>
          <a href="/" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Результат поиска</a>
          <p></p>
          <a href="/" class="btn btn-outline-danger btn-sm" role="button" aria-pressed="true">Удалить</a>
        </div>
      </div>
    {% endfor %}
</div>      


{% endblock %}

service/templates/mistake.html
ЖЕТСКАЯ ОШИБКА

service/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #b7d7e8;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('index.index') }}">Ловец аномалий учета основных средств</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{{ url_for('index.index') }}">Загрузка</a>
        </div>
      </div>
    </div>
</nav>
  